### ISSUE TITLE
hello sir  

### ISSUE THREAD

**Issue by saranzeb** [phuselab/pyVHR#28] opened 2021-11-05 05:46 UTC
hello sir   need a little help regarding 
Do we need the ground truth values for notebook (basic demo and factory demo  ) files if yes from where we can get it i.e. from where we can get the BVP files for BVPdateDIR ?  and what about the other datasets like LGI_PPGI etc  do they have the ground truth files ie its bvp and ecg files or we have to create by ourselves  
Another question the IDI files containing some Videos' s what about other (xml) files they have like 
cms50_stream_handler
andc
v_camera_sensor_timer_stream_handler 
they are having the BVP or BPM and time values ?

**Comment by vcuculo** [comment] 2021-11-05 08:37
Duplicate of #29

**Closed by vcuculo** 2021-11-05 08:37 UTC
