### ISSUE TITLE
EnvironmentFileNotFound Error

### ISSUE THREAD

**Issue by rhaizer** [phuselab/pyVHR#26] opened 2021-10-22 05:03 UTC
`conda env create --file https://github.com/phuselab/pyVHR/blob/pyVHR_CPU/pyVHR_CPU_env.yml`

Gives the following error:

EnvironmentFileNotFound:

OS: Windows10

**Comment by vcuculo** [comment] 2021-11-05 08:39
I close this issue since no updates from the author. Please feel free to reopen it if the problem is still present. Thank you

**Closed by vcuculo** 2021-11-05 08:39 UTC

**Comment by Lokesh-Vakkalakula** [comment] 2022-02-04 17:57
Unfortunately I am facing similar issue in windows 10. Have used anaconda and then downloaded minianaconda, but same issue. Any leads would be helpful. Please check.

conda env create --file https://raw.githubusercontent.com/phuselab/pyVHR/pyVHR_CPU/pyVHR_CPU_env.yml

######error#######
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - ncurses=6.2
  - libidn2=2.3.2
  - nettle=3.7.3
  - _openmp_mutex=4.5
  - libgcc-ng=11.2.0
  - libstdcxx-ng=11.2.0
  - libunistring=0.9.10
  - lame=3.100
  - openh264=2.1.0
  - ld_impl_linux-64=2.35.1
  - nss=3.69
  - libgomp=11.2.0
  - gmp=6.2.1
  - libtasn1=4.16.0
  - gnutls=3.6.15
  - nspr=4.30
  - libuuid=2.32.1
  - readline=8.1

**Comment by wgb-10** [comment] 2022-04-10 08:46
The issue is still present, however, the list of packages has reduced

![image](https://user-images.githubusercontent.com/55624355/162610263-fdf38aad-4fdf-4887-a738-27e2005f4d86.png)
